// Code generated by errunchecked-test. DO NOT EDIT.

package a

import "github.com/graxinc/errutil"

// Generated files are skipped entirely: a direct wrap that would otherwise be
// flagged stays silent.
func generatedDirectWrap() error {
	return errutil.With(returnsErr())
}
