// Code generated by errwrap-test. DO NOT EDIT.

package a

import (
	"errors"

	"github.com/graxinc/errutil"
)

// Generated files are skipped entirely: unwrapped returns and wrapped
// constructors that would otherwise be flagged stay silent.
func generatedUnwrapped(err error) error {
	return err
}

func generatedWrapNew() error {
	return errutil.With(errors.New(""))
}
