// Code generated by errunchecked-test. DO NOT EDIT.

package dep

import "github.com/graxinc/errutil"

// GeneratedAlwaysErr still exports a fact even though its file is generated:
// generated callees can vouch for handwritten callers.
func GeneratedAlwaysErr() error { // want GeneratedAlwaysErr:`nonNilError\[0\]`
	return errutil.New(nil)
}
