name: ci
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2
          args: --timeout=10m

      - name: golangci-lint tools
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2
          working-directory: tools
          args: --timeout=10m

      - name: mod tidy check
        run: go mod tidy --diff

      - name: mod tidy check tools
        working-directory: tools
        run: go mod tidy --diff

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Test
        run: |
          go test ./... -count 1 -race -timeout 20m

      - name: Test tools
        working-directory: tools
        run: |
          go test ./... -count 1 -race -timeout 20m
